name = "coolpack"
author = "huantian"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebff6cb445fe69239c8dcf35f1e55a239a360e150ffedafe7e4bc0613b05cc5f"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
