name = "coolpack"
author = "huantian"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc3552f074dfdfcb4afb72d33baeb79b1fe42f684aedc1054ce193a47474c882"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
